name: Run flow
on:
  workflow_dispatch:
    inputs:
      prefect-version:
        description: Prefect version for flows
        required: true
        default: '2.*'
        type: string
      flow:
        description: Flow to run
        required: true
        type: choice
        options: ['healthcheck.py', 'hello_subflow.py', 'parametrized.py']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Python dependencies
        run: |
          pip install -U prefect==${{ github.event.inputs.prefect-version }}

      - name: Prefect Cloud login
        run: |
          prefect config set PREFECT_API_KEY=${{ secrets.PREFECT_API_KEY}} 
          prefect config set PREFECT_API_URL=${{ secrets.PREFECT_API_URL}}
      - name: Run the flow
        run: python flows/${{ github.event.inputs.flow }}
